import type { Metadata } from "next";
import "./globals.css";

// The Greed font itself is loaded via a plain @font-face in globals.css,
// not next/font/local -- every component's font-family comes from a
// design token (the literal string 'Greed Standard-TRIAL'), and
// next/font/local generates its own different family name that those
// tokens have no way to reference. A plain @font-face targeting that
// exact literal name is what actually makes the tokens resolve, and
// works in both the real app and Storybook (which doesn't run through
// Next's font pipeline at all).

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
